export const SITE_ASSET_FALLBACKS = {
  "home.hero.method.desktop": "/img/rebel-r2/rebel/home/hero/method-desktop.webp",
  "home.hero.method.mobile": "/img/rebel-r2/rebel/home/hero/method-mobile.webp",
  "home.hero.face.desktop": "/img/rebel-r2/rebel/home/hero/face-glow-desktop.webp",
  "home.hero.face.mobile": "/img/rebel-r2/rebel/home/hero/face-glow-mobile.webp",
  "home.hero.body.desktop": "/img/rebel-r2/rebel/home/hero/body-forma-desktop.webp",
  "home.hero.body.mobile": "/img/rebel-r2/rebel/home/hero/body-forma-mobile.webp",
  "home.hero.laser.desktop": "/img/rebel-r2/rebel/home/hero/laser-icepolar-desktop.webp",
  "home.hero.laser.mobile": "/img/rebel-r2/rebel/home/hero/laser-icepolar-mobile.webp",
  "home.hero.longevity.desktop": "/img/rebel-r2/rebel/home/hero/longevity-desktop.webp",
  "home.hero.longevity.mobile": "/img/rebel-r2/rebel/home/hero/longevity-mobile.webp",
  "home.hero.lamination.desktop": "/img/rebel-r2/rebel/home/hero/lamination-desktop.webp",
  "home.hero.lamination.mobile": "/img/rebel-r2/rebel/home/hero/lamination-mobile.webp",
  "home.hero.epigenetics.desktop": "/img/rebel-r2/rebel/home/hero/epigenetics-desktop.webp",
  "home.hero.epigenetics.mobile": "/img/rebel-r2/rebel/home/hero/epigenetics-mobile.webp",
  "home.hero.technologies.desktop": "/img/rebel-r2/rebel/home/hero/technologies-desktop.webp",
  "home.hero.technologies.mobile": "/img/rebel-r2/rebel/home/hero/technologies-mobile.webp",
  "home.hero.studio.desktop": "/img/rebel-r2/rebel/home/hero/studio-desktop.webp",
  "home.hero.studio.mobile": "/img/rebel-r2/rebel/home/hero/studio-mobile.webp",
  "journeys.glow.hero.desktop": "/img/rebel-r2/rebel/journeys/glow/hero-desktop.webp",
  "journeys.glow.hero.mobile": "/img/rebel-r2/rebel/journeys/glow/hero-mobile.webp",
  "journeys.forma.hero.desktop": "/img/rebel-r2/rebel/journeys/forma/hero-desktop.webp",
  "journeys.forma.hero.mobile": "/img/rebel-r2/rebel/journeys/forma/hero-mobile.webp",
  "journeys.liberta.hero.desktop": "/img/rebel-r2/rebel/journeys/liberta/hero-desktop.webp",
  "journeys.liberta.hero.mobile": "/img/rebel-r2/rebel/journeys/liberta/hero-mobile.webp",
  "journeys.longevity.hero.desktop": "/img/rebel-r2/rebel/journeys/longevity/hero-desktop.webp",
  "journeys.longevity.hero.mobile": "/img/rebel-r2/rebel/journeys/longevity/hero-mobile.webp",
  "services.method.consultation.mobile": "/img/rebel-r2/rebel/services/method/consultation-mobile.webp",
  "services.face.skinTexture.mobile": "/img/rebel-r2/rebel/services/face/skin-texture-mobile.webp",
  "services.face.activesTopshot.mobile": "/img/rebel-r2/rebel/services/face/actives-topshot-mobile.webp",
  "services.laser.handpiece.desktop": "/img/rebel-r2/rebel/services/laser/handpiece-desktop.webp",
  "services.laser.handpiece.mobile": "/img/rebel-r2/rebel/services/laser/handpiece-mobile.webp",
  "services.lamination.detail.desktop": "/img/rebel-r2/rebel/services/lamination/detail-desktop.webp",
  "services.lamination.detail.mobile": "/img/rebel-r2/rebel/services/lamination/detail-mobile.webp",
  "services.epigenetics.detail.desktop": "/img/rebel-r2/rebel/services/epigenetics/detail-desktop.webp",
  "services.epigenetics.detail.mobile": "/img/rebel-r2/rebel/services/epigenetics/detail-mobile.webp",
  "services.technologies.detail.desktop": "/img/rebel-r2/rebel/services/technologies/detail-desktop.webp",
  "services.technologies.detail.mobile": "/img/rebel-r2/rebel/services/technologies/detail-mobile.webp",
  "services.manicure.hero.desktop": "/img/rebel-r2/rebel/services/manicure/hero-desktop.webp",
  "services.manicure.detail.mobile": "/img/rebel-r2/rebel/services/manicure/detail-mobile.webp",
  "services.massage.hero.desktop": "/img/rebel-r2/rebel/services/massage/hero-desktop.webp",
  "services.massage.detail.mobile": "/img/rebel-r2/rebel/services/massage/detail-mobile.webp",
  "services.pedicure.hero.desktop": "/img/rebel-r2/rebel/services/pedicure/hero-desktop.webp",
  "services.pedicure.detail.mobile": "/img/rebel-r2/rebel/services/pedicure/detail-mobile.webp",
  "services.draining.hero.desktop": "/img/rebel-r2/rebel/services/draining/hero-desktop.webp",
  "services.draining.detail.mobile": "/img/rebel-r2/rebel/services/draining/detail-mobile.webp",
  "brand.cut.desktop": "/img/rebel-r2/rebel/brand/rebel-cut-desktop.webp",
  "brand.cut.mobile": "/img/rebel-r2/rebel/brand/rebel-cut-mobile.webp",
  "brand.prism.desktop": "/img/rebel-r2/rebel/brand/rebel-prism-desktop.webp",
  "brand.prism.mobile": "/img/rebel-r2/rebel/brand/rebel-prism-mobile.webp",
  "brand.texture.pink": "/img/rebel-r2/rebel/brand/rebel-prism-desktop.webp",
  "brand.texture.violet": "/img/rebel-r2/rebel/brand/rebel-cut-desktop.webp",
  "territory.racconigi": "/img/rebel-r2/rebel/territory/racconigi-wide.webp",
  "territory.langhe": "/img/rebel-r2/rebel/territory/langhe-wide.webp",
  "territory.roero": "/img/rebel-r2/rebel/territory/roero-wide.webp",
  "territory.bra": "/img/rebel-r2/rebel/territory/bra-wide.webp",
  "studio.professional.desktop": "/img/rebel-r2/rebel/studio/professional-desktop.webp",
  "studio.professional.mobile": "/img/rebel-r2/rebel/studio/professional-mobile.webp",
  "studio.reception": "/img/rebel-r2/rebel/studio/professional-desktop.webp",
  "technologies.laser.detail": "/img/rebel-r2/rebel/services/laser/handpiece-desktop.webp",
} as const;

export type SiteAssetSlot = keyof typeof SITE_ASSET_FALLBACKS;

export function getSiteAssetFallback(slot: string): string | null {
  return Object.prototype.hasOwnProperty.call(SITE_ASSET_FALLBACKS, slot)
    ? SITE_ASSET_FALLBACKS[slot as SiteAssetSlot]
    : null;
}

